{
  description = "Package oh-my-pi from source and upstream binaries";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      rust-overlay,
    }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ rust-overlay.overlays.default ];
      };
      lib = pkgs.lib;

      pname = "oh-my-pi";
      sourceData = builtins.fromJSON (builtins.readFile ./hashes.json);
      binData = builtins.fromJSON (builtins.readFile ./bin-hashes.json);

      runtimeLibraryPath = lib.makeLibraryPath [
        pkgs.stdenv.cc.cc.lib
        pkgs.zlib
      ];
      installCheckEnvironment = ''
        export HOME="$TMPDIR/check-home"
        export XDG_DATA_HOME="$TMPDIR/check-xdg-data"
        mkdir -p "$HOME" "$XDG_DATA_HOME/omp"
      '';
      installShellCompletions = ''
        completion_dir="$TMPDIR/completions"
        completion_runtime_dir="$TMPDIR/completion-runtime"
        rm -rf "$completion_dir" "$completion_runtime_dir"
        mkdir -p "$completion_dir" "$completion_runtime_dir/home" "$completion_runtime_dir/xdg"

        HOME="$completion_runtime_dir/home" XDG_DATA_HOME="$completion_runtime_dir/xdg" \
          "$out/bin/omp" completions bash > "$completion_dir/omp.bash"
        HOME="$completion_runtime_dir/home" XDG_DATA_HOME="$completion_runtime_dir/xdg" \
          "$out/bin/omp" completions zsh > "$completion_dir/_omp"
        HOME="$completion_runtime_dir/home" XDG_DATA_HOME="$completion_runtime_dir/xdg" \
          "$out/bin/omp" completions fish > "$completion_dir/omp.fish"

        installShellCompletion --bash --name omp "$completion_dir/omp.bash"
        installShellCompletion --zsh --name _omp "$completion_dir/_omp"
        installShellCompletion --fish --name omp.fish "$completion_dir/omp.fish"
      '';
      installCheckCompletions = ''
        test -s "$out/share/bash-completion/completions/omp"
        test -s "$out/share/zsh/site-functions/_omp"
        test -s "$out/share/fish/vendor_completions.d/omp.fish"
      '';
      relaxBunEngine = ''
        # Relax engines.bun to match the bun used for compilation. Upstream may
        # require a newer bun than nixpkgs carries, but the generated CLI runs
        # correctly with the compiler's embedded runtime.
        sed -i 's/"bun": ">=[0-9.]*"/"bun": ">='"$(bun --version)"'"/' \
          packages/utils/package.json
      '';
      useLooseNativeAddons = ''
        # Nix can keep native addons in the immutable store next to the compiled
        # executable. Do not follow upstream's release path that embeds a
        # compressed native archive into `omp`; the upstream loader can also
        # load loose `pi_natives.*.node` files from the executable directory.
        #
        # Patch the generator instead of individual build-binary.ts call sites:
        # upstream has renamed the package scripts before (`embed:native` ->
        # `gen:native`), but the release build still routes native embedding
        # through this script.
        cat > packages/natives/scripts/embed-native.ts <<'EOF'
        import * as fs from "node:fs/promises";
        import * as path from "node:path";

        const nativeDir = path.join(import.meta.dir, "../native");
        const outputPath = path.join(nativeDir, "embedded-addon.js");
        const archivePrefix = "embedded-addons.";
        const archiveSuffix = ".tar.gz";

        await Bun.write(
        	outputPath,
        	`// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
        // Patched by oh-my-pi-nix: native addons are shipped as loose .node files.

        export const embeddedAddon = null;
        `,
        );

        try {
        	const entries = await fs.readdir(nativeDir);
        	await Promise.all(
        		entries
        			.filter(entry => entry.startsWith(archivePrefix) && entry.endsWith(archiveSuffix))
        			.map(entry => fs.unlink(path.join(nativeDir, entry))),
        	);
        } catch (err) {
        	if (!err || typeof err !== "object" || !("code" in err) || err.code !== "ENOENT") {
        		throw err;
        	}
        }
        EOF
      '';
      useNixBiomeFormatter = ''
        # v16.1.19 invokes Biome while generating the legacy pi registry. Use
        # the Nix-packaged Biome instead of the npm CLI binary, and normalize the
        # upstream config key that Biome 2.4.16 rejects.
        substituteInPlace biome.json \
          --replace-fail '"preset": "recommended",' '"recommended": true,'
        substituteInPlace packages/coding-agent/scripts/generate-legacy-pi-bundled-registry.ts \
          --replace-fail '["bunx", "biome", "check", "--write", ...targets]' \
            '["${pkgs.biome}/bin/biome", "check", "--write", ...targets]'
      '';
      commonMeta = {
        description = "AI coding agent for the terminal";
        homepage = "https://github.com/can1357/oh-my-pi";
        license = lib.licenses.mit;
        mainProgram = "omp";
        platforms = [ system ];
      };

      sourceVersion = sourceData.version;
      sourceRev = sourceData.srcRev;
      rustToolchainChannel = "nightly-2026-04-29";
      rustTarget = "x86_64-unknown-linux-gnu";
      sourceSrc = pkgs.fetchgit {
        url = "https://github.com/can1357/oh-my-pi.git";
        rev = sourceRev;
        deepClone = false;
        fetchSubmodules = false;
        fetchTags = false;
        leaveDotGit = false;
        hash = sourceData.srcHash;
      };

      toolchainWithTarget =
        let
          nightlyDateMatch = builtins.match "nightly-(.+)" rustToolchainChannel;
          stableVersionMatch = builtins.match "[0-9]+\\.[0-9]+\\.[0-9]+" rustToolchainChannel;
          baseToolchain =
            if nightlyDateMatch != null then
              pkgs.rust-bin.nightly."${builtins.head nightlyDateMatch}".minimal
            else if rustToolchainChannel == "nightly" then
              pkgs.rust-bin.selectLatestNightlyWith (toolchain: toolchain.minimal)
            else if rustToolchainChannel == "stable" then
              pkgs.rust-bin.stable.latest.minimal
            else if rustToolchainChannel == "beta" then
              pkgs.rust-bin.beta.latest.minimal
            else if stableVersionMatch != null then
              pkgs.rust-bin.stable."${rustToolchainChannel}".minimal
            else
              throw "Unsupported rustToolchainChannel: ${rustToolchainChannel}";
        in
        baseToolchain.override {
          targets = [ rustTarget ];
        };

      rustPlatform = pkgs.makeRustPlatform {
        cargo = toolchainWithTarget;
        rustc = toolchainWithTarget;
      };

      bunDeps = pkgs.stdenvNoCC.mkDerivation {
        name = "${pname}-${sourceVersion}-bun-deps";
        src = sourceSrc;

        nativeBuildInputs = [ pkgs.bun ];
        strictDeps = true;
        dontConfigure = true;
        dontFixup = true;
        postPatch = relaxBunEngine;
        impureEnvVars = lib.fetchers.proxyImpureEnvVars;

        buildPhase = ''
          runHook preBuild

          export HOME="$TMPDIR/home"
          export XDG_CACHE_HOME="$TMPDIR/xdg-cache"
          export BUN_INSTALL_CACHE_DIR="$TMPDIR/bun-install-cache"
          mkdir -p "$HOME" "$XDG_CACHE_HOME" "$BUN_INSTALL_CACHE_DIR"

          bun install --frozen-lockfile --linker=hoisted --backend=copyfile

          runHook postBuild
        '';

        installPhase = ''
          runHook preInstall

          mkdir -p "$out"
          cp -a node_modules "$out/node_modules"

          runHook postInstall
        '';

        outputHashMode = "recursive";
        outputHash = sourceData.bunHash;
      };

      cargoDeps = rustPlatform.fetchCargoVendor {
        src = sourceSrc;
        hash = sourceData.cargoHash;
      };

      ohMyPi = pkgs.stdenv.mkDerivation {
        inherit pname cargoDeps;
        version = sourceVersion;
        src = sourceSrc;

        nativeBuildInputs = [
          pkgs.autoPatchelfHook
          pkgs.bun
          pkgs.biome
          pkgs.makeWrapper
          pkgs.installShellFiles
          pkgs.pkg-config
          toolchainWithTarget
          rustPlatform.cargoSetupHook
        ];

        buildInputs = [
          pkgs.stdenv.cc.cc.lib
          pkgs.zlib
        ];
        strictDeps = true;
        dontStrip = true;
        postPatch = ''
          ${relaxBunEngine}
          ${useLooseNativeAddons}
          ${useNixBiomeFormatter}
        '';

        buildPhase = ''
          runHook preBuild

          export HOME="$TMPDIR/home"
          export XDG_CACHE_HOME="$TMPDIR/xdg-cache"
          export BUN_INSTALL_CACHE_DIR="$TMPDIR/bun-install-cache"
          export CARGO_TARGET_DIR="$TMPDIR/cargo-target"
          mkdir -p "$HOME" "$XDG_CACHE_HOME" "$BUN_INSTALL_CACHE_DIR" "$CARGO_TARGET_DIR"
          export LD_LIBRARY_PATH="${lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib ]}"
          export LIBCLANG_PATH="${pkgs.libclang.lib}/lib"

          cp -a ${bunDeps}/node_modules ./node_modules
          chmod -R u+w ./node_modules
          substituteInPlace node_modules/@napi-rs/cli/dist/cli.js \
            --replace-fail '#!/usr/bin/env node' '#!${pkgs.bun}/bin/bun'

          CI=1 TARGET_VARIANTS="baseline modern" bun run ci:build:native
          bun --cwd=packages/coding-agent run build

          runHook postBuild
        '';

        installPhase = ''
          runHook preInstall

          install -Dm755 packages/coding-agent/dist/omp "$out/lib/omp/omp"
          install -Dm755 packages/natives/native/pi_natives.linux-x64-baseline.node \
            "$out/lib/omp/pi_natives.linux-x64-baseline.node"
          install -Dm755 packages/natives/native/pi_natives.linux-x64-modern.node \
            "$out/lib/omp/pi_natives.linux-x64-modern.node"
          makeWrapper "$out/lib/omp/omp" "$out/bin/omp" \
            --set PI_SKIP_VERSION_CHECK 1 \
            --prefix LD_LIBRARY_PATH : "${runtimeLibraryPath}"
          install -Dm644 LICENSE "$out/share/licenses/${pname}/LICENSE"

          runHook postInstall
        '';

        preFixup = ''
          installShellCompletionsHook() {
            ${installShellCompletions}
          }
          postFixupHooks+=(installShellCompletionsHook)
        '';

        doInstallCheck = true;
        installCheckPhase = ''
          runHook preInstallCheck

          ${installCheckEnvironment}
          smoke_output=$("$out/bin/omp" --smoke-test)
          if [ "$smoke_output" != "smoke-test: ok" ]; then
            echo "unexpected smoke test output: $smoke_output"
            exit 1
          fi

          ${installCheckCompletions}

          test -x "$out/lib/omp/pi_natives.linux-x64-baseline.node"
          test -x "$out/lib/omp/pi_natives.linux-x64-modern.node"
          if [ -e "$XDG_DATA_HOME/omp/natives" ] || [ -e "$HOME/.omp/natives" ]; then
            echo "omp wrote native addons to a user cache"
            exit 1
          fi

          runHook postInstallCheck
        '';

        passthru = {
          inherit bunDeps cargoDeps toolchainWithTarget;
        };

        meta = commonMeta;
      };

      binVersion = binData.version;
      binAssetNames = {
        x86_64-linux = "omp-linux-x64";
      };
      binAssetName = binAssetNames.${system} or (throw "oh-my-pi-bin is not packaged for ${system}");
      binHash = binData.hashes.${system} or (throw "missing oh-my-pi-bin hash for ${system}");
      binSrc = pkgs.fetchurl {
        url = "https://github.com/can1357/oh-my-pi/releases/download/v${binVersion}/${binAssetName}";
        hash = binHash;
      };

      ohMyPiBin = pkgs.stdenv.mkDerivation {
        pname = "${pname}-bin";
        version = binVersion;
        src = binSrc;

        nativeBuildInputs = [
          pkgs.autoPatchelfHook
          pkgs.makeWrapper
          pkgs.installShellFiles
        ];
        buildInputs = [
          pkgs.stdenv.cc.cc.lib
          pkgs.zlib
        ];
        strictDeps = true;
        dontUnpack = true;
        dontConfigure = true;
        dontBuild = true;
        dontStrip = true;

        installPhase = ''
          runHook preInstall

          install -Dm755 "$src" "$out/lib/omp/omp"
          makeWrapper "$out/lib/omp/omp" "$out/bin/omp" \
            --set PI_SKIP_VERSION_CHECK 1 \
            --prefix LD_LIBRARY_PATH : "${runtimeLibraryPath}"

          runHook postInstall
        '';

        preFixup = ''
          installShellCompletionsHook() {
            ${installShellCompletions}
          }
          postFixupHooks+=(installShellCompletionsHook)
        '';

        doInstallCheck = true;
        installCheckPhase = ''
          runHook preInstallCheck

          ${installCheckEnvironment}
          smoke_output=$("$out/bin/omp" --smoke-test)
          if [ "$smoke_output" != "smoke-test: ok" ]; then
            echo "unexpected smoke test output: $smoke_output"
            exit 1
          fi

          ${installCheckCompletions}

          runHook postInstallCheck
        '';

        meta = commonMeta;
      };
    in
    {
      formatter.${system} = pkgs.nixfmt-rfc-style;

      packages.${system} = {
        default = ohMyPi;
        "oh-my-pi" = ohMyPi;
        "oh-my-pi-bin" = ohMyPiBin;
      };

      apps.${system} = {
        default = {
          type = "app";
          program = "${ohMyPi}/bin/omp";
        };
        "oh-my-pi" = {
          type = "app";
          program = "${ohMyPi}/bin/omp";
        };
        "oh-my-pi-bin" = {
          type = "app";
          program = "${ohMyPiBin}/bin/omp";
        };
      };
    };
}
